### PR TITLE
Remove `protobuf-compiler` pip pakacge

### PR DESCRIPTION
**Pull request by TarekkMA**
fixes: #88

### CODE REVIEW

**Comment by TarekkMA** [comment]
@david-allison-1 The checks are green. should I also remove the pyenv/protobuf scripts, since they are not used anymore?

**Comment by TarekkMA** [comment]
This PR will shave about 10 minutes in CI. A step into the right direction 🎉

**Review by david-allison-1 — APPROVED** [review]
LGTM

**Comment by david-allison-1** [comment]
> @david-allison-1 The checks are green. should I also remove the pyenv/protobuf scripts, since they are not used anymore?

Sure! I'll add a follow-up isue

**Pull request merged**
