### PR TITLE
bump gradle wrapper version

### PR DESCRIPTION
**Pull request by TarekkMA**
I was facing issues running gradle from command line using the current wrapper version.

#9

### CODE REVIEW

**Comment by TarekkMA** [comment]
I don't know should I keep working on this PR or make multiple?

I prefer making it one PR until I can figure out the build system for this project and document any issues I may encounter

**Comment by david-allison-1** [comment]
Totally up to you - this is still beta software, so let me know what you'd prefer doing, no need for anything to get in the way.

**Comment by TarekkMA** [comment]
Let's make it one PR for simplifying the process of setting the environment.

**Comment by mikehardy** [comment]
gradle is on 6.8.3 now

**Comment by TarekkMA** [comment]
Should we make it match that? I did only bump it until it worked. Not sure if anything would be affected.

**Comment by mikehardy** [comment]
My personal rules for dependency updates:

If changing dependency versions, always look for the release notes on the dependency and bump it to current stable. 

The only exceptions to moving to current stable is if there is some deprecation we need to handle that we cannot yet (then log a deprecation / forward-port issue for future) or if there is an upstream bug blocking adoption of current stable, at which point you subscribe to that bug (or log if if needed!) and you update to the most recent version possible with a link in the code to the upstream issue stating the version affected and that it can be increased when the issue is resolved

**Comment by mikehardy** [comment]
There is an implication to your last part "Not sure if anything would be affected" - that's the point, you are already in there making changes, *you* are responsible for seeing if anything is affected. As long as you are already doing that, might as well go all the way to current right?

**Comment by TarekkMA** [comment]
Yes, you're right that does make sense.

**Review by mikehardy — APPROVED** [review]
I approve these 2 changed characters :laughing:

**Comment by TarekkMA** [comment]
I will work on the other PR It does have the same commits as this one.

**Pull request closed without merging**
